[novelpub]
url = "https://www.novelpub.com"
sourcePath = "novelpub.com/novelpub.toml"

[allnovelfull]
url = "https://allnovelfull.net"
sourcePath = "allnovelfull.net/allnovelfull.toml"

[noveltrust]
url = "https://noveltrust.com"
sourcePath = "noveltrust.com/noveltrust.toml"